version: '3.8'

services:
  db:
    container_name: todo-postgres-1
    image: postgres:12.1-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
  pgadmin:
    container_name: todo-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@todo.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - "3005:80"
  api:
    container_name: todo_api
    build:
      context: ./api
    ports:
      - "3006:80"
    volumes:
      - ./api:/app
      - /app/node_modules
    env_file:
      - ./api/.env
    depends_on:
      - db
  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile-prod
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
    depends_on:
      - db
      - api
