FROM node:12.19.0-alpine3.9 AS dev
WORKDIR /app

COPY package.json ./
RUN npm install

COPY . /app
RUN npm run build

FROM nginx:alpine
COPY ./nginx.conf /etc/nginx.conf
RUN rm -rf /usr/share/nginx/html/*
COPY --from=dev /app/.next /usr/share/nginx/html

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
