FROM node:12.19.0-alpine3.9 AS dev
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn

COPY . /app
RUN yarn build

FROM nginx:alpine
COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf
RUN rm -rf /usr/share/nginx/html/*
COPY --from=dev /app/out /usr/share/nginx/html

EXPOSE 3000 80
CMD ["nginx", "-g", "daemon off;"]
